baseurl = "https://yakkl.com"
copyright = "Copyright (c) 2019 Yakkl.com."
defaultContentLanguage = "en"
destination = "../dist/"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
metaDataFormat = "yaml"
paginate = 10
pluralizeListTitles = false
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "monokai"
relativeURLs = false
title = "Yakkl.com"
[blackfriday]
angledQuotes = false
hrefTargetBlank = false
latexDashes = true
plainIDAnchors = true
[[menu.docs]]
name = "Organizations"
weight = 7
[[menu.docs]]
name = "Quick Start"
weight = 2
[[menu.docs]]
name = "Welcome"
weight = 1
[[menu.footer]]
name = "Company"
weight = 2
[[menu.footer]]
name = "Product"
weight = 1
[[menu.main]]
identifier = "useraccount"
name = "My Account"
url = "https://yakkl.com/settings"
weight = 5
[[menu.main]]
identifier = "signup"
name = "Sign up"
url = "https://yakkl.com/signup"
weight = 8
[[menu.main]]
identifier = "userdashboard"
name = "Dashboard"
url = "https://yakkl.com/dashboard"
weight = 7
[[menu.main]]
identifier = "login"
name = "Login"
url = "https://yakkl.com/login"
weight = 6
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true
[outputFormats.OpenSearch]
baseName = "opensearch"
isPlainText = true
mediaType = "application/xml"
notAlternative = true
[outputFormats.Redirects]
baseName = "redirects"
isPlainText = true
mediatype = "application/json"
notAlternative = true
[outputs]
home = ["HTML", "RSS", "OpenSearch", "Algolia", "Redirects"]
[params]
dateformat = "January 2, 2006"
description = "An open-source Secure Team Collaboration product."
ghrepo = "https://github.com/yakkl/yakkl.com"
ghrepo_edit = "https://github.com/yakkl/yakkl.com/edit/master/hugo/content/"
ghrepo_new = "https://github.com/yakkl/yakkl.com/issues/new"
gtmid = "GTM-MRLTPV7"
images = ["/uploads/2018/01/OGimage-01-3x.jpg"]
mixpanelid = ""
[params.algolia]
params = ["tags", "categories", "authors"]
vars = ["date", "description", "dir", "path", "expirydate", "fuzzywordcount", "keywords", "kind", "lang", "lastmod", "permalink", "publishdate", "readingtime", "relpermalink", "summary", "title", "type", "url", "weight", "wordcount", "section"]
[params.cloudinary]
cloud_name = "yakkl-demo"
use_upload = false
[params.cloudinary.lazysizes]
enabled = false
[params.cloudinary.presets.content]
max_width = 1920
min_width = 320
quality = 80
sizes = "auto"
steps = 10
width = 640
[params.cloudinary.presets.default]
quality = 80
[params.cloudinary.presets.feature]
max_width = 1920
min_width = 320
quality = 80
sizes = "(max-width: 76px) 100%, 800px"
steps = 10
width = 640
[related]
includeNewer = true
threshold = 10
toLower = true
[[related.indices]]
name = "Section"
weight = 200
[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name = "categories"
weight = 150
[[related.indices]]
name = "tags"
weight = 100
[[related.indices]]
name = "date"
pattern = "2006"
weight = 10
[social]
email = "support@yakkl.com"
twitter = "yakklofficial"
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
